apiVersion: unikorn-cloud.org/v1alpha1
kind: VirtualKubernetesClusterApplicationBundle
metadata:
  name: virtual-kubernetes-cluster-1.1.0
  labels:
    {{- include "unikorn.labels" . | nindent 4 }}
spec:
  version: 1.1.0
  applications:
  - name: virtualcluster
    reference:
      kind: HelmApplication
      name: {{ include "resource.id" "virtualcluster" }}
      version: 0.1.0
