# Set the global container repo.
repository: ghcr.io

# Set the global container repo organization.
organization: nscaledev

# Set the global container tag.
# Defaults to the chart revision, which should be in lock-step with the
# actual release.
# tag:

# Set the image pull secret on the service accounts of all the controllers.
# This is an alternative to dockerConfigs, but unlikely to play ball with
# ArgoCD as it's a foreign object that needs pruning.
imagePullSecret: ~

# Cluster manager controller specific configuration.
clusterManagerController:
  # Allows override of the global default image.
  image:

# Cluster controller specific configuration.
clusterController:
  # Allows override of the global default image.
  image:

# Virtual cluster controller specific configuration.
virtualClusterController:
  # Allows override of the global default image.
  image: ~
  # Sets the DDNS domain virtual clusters will be part of
  virtualKubernetesClusterDomain: ~
  # Tells the controller to use a nodeSelector when creating vClusters
  nodeSelectorLabel: ""

# Monitor specific configuration.
monitor:
  # Allows override of the global default image.
  image:

# Sets the DNS hosts/X.509 Certs.
kubernetes:
  host: unikorn.unikorn-cloud.org

# REST server specific configuration.
server:
  # Allows override of the global default image.
  image:

ingress:
  # Sets the ingress class to use.
  # class: nginx

  # clusterIssuer to use.
  clusterIssuer: unikorn-issuer

  # If true, will add the external DNS hostname annotation.
  externalDns: false

# Allows CORS to be configured/secured
# cors:
#   # Broswers must send requests from these origin servers, defaults to * if not set.
#   allowOrigin: ['*']
#   # How long to cache the CORS preflight for, mostly useless as browsers override this.
#   maxAge: 86400

# CA file if using self signed/private certificates.
# ca:
#   secretNamespace: ~
#   secretName: ~

identity:
  # OIDC issuer used to discover OIDC configuration and verify access tokens.
  host: identity.unikorn-cloud.org

region:
  # Region controller URL.
  host: region.unikorn-cloud.org

# Sets the OTLP endpoint for shipping spans.
# otlp:
#   endpoint: jaeger-collector.default:4318

# Defines Prometheus monitoring integration.
monitoring:
  # Enable monitoring, ensure Prometheus is installed first to define the CRDs.
  enabled: false

  # Set the namespace to generate the service monitor into.
  namespace: monitoring

  # Define service monitor configuration.
  serviceMonitor:

    # Labels required to be selected by Prometheus, this is compatible with
    # kube-prometheus defaults.
    labels:
      release: prometheus
